#################### Default Parameters ################################
favicon = "images/favicon.png"
logo = "images/tree_code_circle.png"
logo_width = "100px"
# OpenGraph / Twitter Card metadata
title = "Nature.In.Paradise"
description = "This is meta description"
author = "Dave Klinges"
images = [ "images/tree_code_circle.png" ] # First image here will be used as fallback if a page has no images of its own
copyright = "Copyright &copy; 2024 David Klinges and [Themefisher](https://themefisher.com). All Rights Reserved."
# search
[search]
enable = true

################################# Sidebar widgets #############################
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


[variables]
font_size = "16px" # default is 16px
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = 'Roboto:wght@100;200;300;400;500;700'
font_primary_type = "sans-serif"


################################# Contact page ################################
[contact]
# Address block
phone = "dklinges9[@]gmail.com"
location = """
370 Prospect Street New Haven, CT 06511, USA
"""
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false
[contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = false
# Form action
## For Formspree.io: Your Form ID URL, e.g. `https://formspree.io/f/{form_id}`
## For Netlify Forms: Path to a custom [success page](https://docs.netlify.com/forms/setup/#success-messages)
action = "https://formspree.io/xjvaeeeo"
  
################################# Google map ##################################
[gmap]
enable = true
gmap_url = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d17701.318162990254!2d47.421622!3d-21.2540904!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x21e62a3ad8e2e425%3A0x5f143faca09f72af!2sCentre%20ValBio!5e1!3m2!1sen!2sbd!4v1727759563665!5m2!1sen!2sbd"


################################# Preloader ###################################
[preloader]
enable = true
preloader = "" # use .png , .svg or .gif image

################################# Cookies #####################################
[cookies]
enable = true

############################# Social Media ########################
[[social]]
icon = "ion-social-github" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://github.com/dklinges9"

[[social]]
icon = "ion-social-google" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://scholar.google.com/citations?user=i9pmQasAAAAJ&hl=en"

[[social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/in/david-klinges-944551111/"

[[social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/thenaturedave"

[[social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/thenaturedave/"

[[social]]
icon = "ion-social-youtube" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.youtube.com/channel/UCMw5wuRqpwiVOH9GaI1TVNA"
